version: '3.7'
services:
  honeyswarm:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - honeyswarm_dev.env
    ports:
      - "80:80"
      - "8181:8181"
    networks:
      honeynet:
        ipv4_address: 10.1.0.101
    volumes:
      - "./honeystates/salt:/opt/honeyswarm/templates/honeystates:rw"
    depends_on: 
      - mongoserver
      - saltmaster
  mongoserver:
    image: mongo:latest
    env_file:
      - honeyswarm_dev.env
    ports:
      - '27017:27017'
    networks:
      honeynet:
        ipv4_address: 10.1.0.102
    volumes:
      - "./dev/mongo:/data/db"
  saltmaster:
    image: "saltstack/salt:latest"
    env_file:
      - honeyswarm_dev.env
    ports:
      - "8000:8000"
      - "4505:4505"
      - "4506:4506"
    networks:
      honeynet:
        ipv4_address: 10.1.0.103
    volumes:
      - "./dev/salt:/etc/salt/pki:rw"
      - "./honeystates:/srv:rw"
  hpfeeds-broker:
    build:
      context: .
      dockerfile: Dockerfile-broker
    container_name: hpfeeds
    ports:
     - "0.0.0.0:10000:10000"
    networks:
      honeynet:
        ipv4_address: 10.1.0.104
    env_file:
      - honeyswarm_dev.env
    command:
     - '/app/bin/hpfeeds-broker'
     - '--endpoint=tcp:port=10000'
     - '--exporter=0.0.0.0:9431'
     - '--auth="mongodb://admin:admin@mongoserver:27017/hpfeeds"'
    depends_on: 
      - mongoserver
networks:
  honeynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24